# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-12 10:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=256)),
                ('serial', models.CharField(blank=True, max_length=256)),
                ('condition', models.CharField(max_length=256)),
                ('lane', models.IntegerField(blank=True, default=999)),
                ('ulid', models.CharField(max_length=30, unique=True)),
                ('series', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=64)),
                ('value', models.FloatField(blank=True, null=True)),
                ('text', models.CharField(default='', max_length=256)),
                ('unit', models.CharField(blank=True, max_length=16)),
                ('index', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ulid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meas.Condition', to_field='ulid')),
            ],
            options={
                'verbose_name_plural': 'entries',
            },
        ),
    ]
