# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-08 05:21
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=256)),
                ('condition', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('item', models.CharField(max_length=64)),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=16)),
            ],
        ),
    ]
