# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-15 09:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='entry',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
