# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-09 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meas', '0003_auto_20170914_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='serial',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
