# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-01 17:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meas', '0005_auto_20171024_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='lane',
        ),
        migrations.AddField(
            model_name='condition',
            name='lane',
            field=models.IntegerField(blank=True, default=999),
        ),
        migrations.AddField(
            model_name='condition',
            name='series',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
