# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-07 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meas', '0006_auto_20171102_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='series',
            field=models.CharField(max_length=256),
        ),
    ]
