# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meas', '0007_auto_20171108_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='index',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='entry',
            name='text',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
