# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-09 00:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meas', '0007_auto_20171107_1616'),
        ('meas', '0007_auto_20171108_0011'),
    ]

    operations = [
    ]
