# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meas', '0009_auto_20171128_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='index',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='entry',
            name='text',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='entry',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
