# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 01:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meas', '0011_auto_20171128_1010'),
        ('meas', '0008_merge_20171109_0959'),
    ]

    operations = [
    ]
